data.raw["assembling-machine"]["assembling-machine-1"].crafting_categories = {"crafting", "basic-crafting", "advanced-crafting", "electronics", "pressing", "advanced-centrifuging-or-crafting", "advanced-centrifuging-or-crafting-or-electromechanics", "quantum-assembling-or-crafting", "woodworking-or-crafting", "electromechanics-or-crafting", "electronics-or-electromechanics", "pressing-or-electromechanics"}
data.raw["assembling-machine"]["assembling-machine-2"].crafting_categories = {"basic-crafting", "crafting", "advanced-crafting", "crafting-with-fluid", "electronics", "electronics-with-fluid", "pressing", "metallurgy-or-assembling", "organic-or-hand-crafting", "organic-or-assembling", "electronics-or-assembling", "cryogenics-or-assembling", "crafting-with-fluid-or-metallurgy", "advanced-centrifuging-or-crafting", "advanced-centrifuging-or-crafting-or-electromechanics", "quantum-assembling-or-crafting", "woodworking-or-crafting", "electromechanics-or-crafting", "biochemistry-or-organic-or-hand-crafting", "biochemistry-or-organic-or-assembling", "woodworking-or-organic-or-assembling", "petrochemistry-or-organic-or-assembling" , "electronics-or-electromechanics", "pressing-or-electromechanics", "quantum-assembling-or-crafting-with-fluid", "advanced-centrifuging-or-crafting-with-fluid"}
data.raw["assembling-machine"]["assembling-machine-3"].crafting_categories = {"basic-crafting", "crafting", "advanced-crafting", "crafting-with-fluid", "electronics", "electronics-with-fluid", "pressing", "metallurgy-or-assembling", "organic-or-hand-crafting", "organic-or-assembling", "electronics-or-assembling", "cryogenics-or-assembling", "crafting-with-fluid-or-metallurgy", "advanced-centrifuging-or-crafting", "advanced-centrifuging-or-crafting-or-electromechanics", "quantum-assembling-or-crafting", "woodworking-or-crafting", "electromechanics-or-crafting", "biochemistry-or-organic-or-hand-crafting", "biochemistry-or-organic-or-assembling", "woodworking-or-organic-or-assembling", "petrochemistry-or-organic-or-assembling", "electronics-or-electromechanics", "pressing-or-electromechanics", "quantum-assembling-or-crafting-with-fluid", "advanced-centrifuging-or-crafting-with-fluid"}
data.raw["assembling-machine"]["chemical-plant"].crafting_categories = {"chemistry", "chemistry-or-cryogenics", "organic-or-chemistry", "hydraulics-or-chemistry", "hydraulics-or-chemistry-or-cryogenics", "petrochemistry-or-organic-or-chemistry", "petrochemistry-or-chemistry", "petrochemistry-or-chemistry-or-cryogenics"}
data.raw["assembling-machine"]["centrifuge"].crafting_categories = {"centrifuging", "advanced-centrifuging-or-centrifuging"}
data.raw["assembling-machine"]["oil-refinery"].crafting_categories = {"oil-processing", "petrochemistry-or-oil-processing"}
data.raw["assembling-machine"]["biochamber"].crafting_categories = {"organic", "organic-or-hand-crafting", "organic-or-assembling", "organic-or-chemistry", "biochemistry-or-organic", "biochemistry-or-organic-or-hand-crafting", "biochemistry-or-organic-or-assembling", "woodworking-or-organic", "woodworking-or-organic-or-assembling", "hydraulics-or-organic", "petrochemistry-or-organic-or-chemistry", "petrochemistry-or-organic-or-assembling", "petrochemistry-or-organic", "organic-or-electromechanics"}
data.raw["assembling-machine"]["cryogenic-plant"].crafting_categories = {"cryogenics", "chemistry-or-cryogenics", "cryogenics-or-assembling", "hydraulics-or-chemistry-or-cryogenics", "petrochemistry-or-chemistry-or-cryogenics"}
data.raw["assembling-machine"]["electromagnetic-plant"].crafting_categories = {"electromagnetics", "electronics", "electronics-with-fluid", "electronics-or-assembling", "electronics-or-electromechanics"}
data.raw["assembling-machine"]["foundry"].crafting_categories = {"metallurgy", "pressing", "crafting-with-fluid-or-metallurgy", "metallurgy-or-assembling", "pressing-or-electromechanics", "metallurgy-2-the-return"}
data.raw.character.character.crafting_categories = {"crafting", "electronics", "pressing", "recycling-or-hand-crafting", "organic-or-hand-crafting", "organic-or-assembling", "advanced-centrifuging-or-crafting", "quantum-assembling-or-crafting", "biochemistry-or-organic-or-hand-crafting", "woodworking-or-crafting", "electromechanics-or-crafting", "advanced-centrifuging-or-crafting-or-electromechanics"}

local function add_tech_effect(tech_name, effect)
    local tech = data.raw.technology[tech_name]
    tech.effects = tech.effects or {}
    table.insert(tech.effects, effect)
  end
  
  add_tech_effect("cryogenic-plant", {type = "unlock-recipe", recipe = "aop-water-freezing"})

  data.raw["assembling-machine"]["crusher"].surface_conditions = nil
data.raw.recipe["automation-science-pack"].category = "quantum-assembling-or-crafting"
data.raw.recipe["logistic-science-pack"].category = "quantum-assembling-or-crafting"
data.raw.recipe["chemical-science-pack"].category = "quantum-assembling-or-crafting"
data.raw.recipe["military-science-pack"].category = "quantum-assembling-or-crafting"
data.raw.recipe["production-science-pack"].category = "quantum-assembling-or-crafting"
data.raw.recipe["utility-science-pack"].category = "quantum-assembling-or-crafting"
data.raw.recipe["space-science-pack"].category = "quantum-assembling-or-crafting"
data.raw.recipe["atomic-bomb"].category = "advanced-centrifuging-or-crafting"
data.raw.recipe["centrifuge"].category = "advanced-centrifuging-or-crafting"
data.raw.recipe["nuclear-reactor"].category = "advanced-centrifuging-or-crafting"
data.raw.recipe["uranium-fuel-cell"].category = "advanced-centrifuging-or-crafting"
data.raw.recipe["nutrients-from-yumako-mash"].category = "biochemistry-or-organic"
data.raw.recipe["nutrients-from-bioflux"].category = "biochemistry-or-organic"
data.raw.recipe["copper-bacteria-cultivation"].category = "biochemistry-or-organic"
data.raw.recipe["iron-bacteria-cultivation"].category = "biochemistry-or-organic"
data.raw.recipe["bioplastic"].category = "biochemistry-or-organic"
data.raw.recipe["biosulfur"].category = "biochemistry-or-organic"
data.raw.recipe["bioflux"].category = "biochemistry-or-organic"
data.raw.recipe["carbon-fiber"].category = "biochemistry-or-organic"
data.raw.recipe["nutrients-from-fish"].category = "biochemistry-or-organic-or-assembling"
data.raw.recipe["nutrients-from-biter-egg"].category = "biochemistry-or-organic-or-assembling"
data.raw.recipe["iron-bacteria"].category = "biochemistry-or-organic-or-hand-crafting"
data.raw.recipe["copper-bacteria"].category = "biochemistry-or-organic-or-hand-crafting"
data.raw.recipe["yumako-processing"].category = "biochemistry-or-organic-or-hand-crafting"
data.raw.recipe["jellynut-processing"].category = "biochemistry-or-organic-or-hand-crafting"
data.raw.recipe["wooden-chest"].category = "woodworking-or-crafting"
data.raw.recipe["small-electric-pole"].category = "woodworking-or-crafting"
data.raw.recipe["shotgun"].category = "woodworking-or-crafting"
data.raw.recipe["combat-shotgun"].category = "woodworking-or-crafting"
data.raw.recipe["agricultural-tower"].category = "woodworking-or-crafting"
data.raw.recipe["nutrients-from-spoilage"].category = "woodworking-or-organic-or-assembling"
data.raw.recipe["wood-processing"].category = "woodworking-or-organic-or-assembling"
data.raw.recipe["burnt-spoilage"].category = "woodworking-or-organic"
data.raw.recipe["lubricant"].category = "hydraulics-or-chemistry"
data.raw.recipe["thruster-fuel"].category = "hydraulics-or-chemistry"
data.raw.recipe["thruster-oxidizer"].category = "hydraulics-or-chemistry"
data.raw.recipe["advanced-thruster-fuel"].category = "hydraulics-or-chemistry"
data.raw.recipe["advanced-thruster-oxidizer"].category = "hydraulics-or-chemistry"
data.raw.recipe["holmium-solution"].category = "hydraulics-or-chemistry"
data.raw.recipe["ice-melting"].category = "hydraulics-or-chemistry"
data.raw.recipe["sulfuric-acid"].category = "hydraulics-or-chemistry-or-cryogenics"
data.raw.recipe["acid-neutralisation"].category = "hydraulics-or-chemistry-or-cryogenics"
data.raw.recipe["steam-condensation"].category = "hydraulics-or-chemistry-or-cryogenics"
data.raw.recipe["biolubricant"].category = "hydraulics-or-organic"
data.raw.recipe["heavy-oil-cracking"].category = "petrochemistry-or-organic-or-chemistry"
data.raw.recipe["light-oil-cracking"].category = "petrochemistry-or-organic-or-chemistry"
data.raw.recipe["solid-fuel-from-light-oil"].category = "petrochemistry-or-chemistry"
data.raw.recipe["solid-fuel-from-heavy-oil"].category = "petrochemistry-or-chemistry"
data.raw.recipe["solid-fuel-from-petroleum-gas"].category = "petrochemistry-or-chemistry"
data.raw.recipe["flamethrower-ammo"].category = "petrochemistry-or-chemistry"
data.raw.recipe["rocket-fuel"].category = "petrochemistry-or-organic-or-assembling"
data.raw.recipe["car"].category = "electromechanics-or-crafting"
data.raw.recipe["tank"].category = "electromechanics-or-crafting"
data.raw.recipe["spidertron"].category = "electromechanics-or-crafting"
data.raw.recipe["logistic-robot"].category = "electromechanics-or-crafting"
data.raw.recipe["construction-robot"].category = "electromechanics-or-crafting"
data.raw.recipe["locomotive"].category = "electromechanics-or-crafting"
data.raw.recipe["cargo-wagon"].category = "electromechanics-or-crafting"
data.raw.recipe["fluid-wagon"].category = "electromechanics-or-crafting"
data.raw.recipe["defender-capsule"].category = "electromechanics-or-crafting"
data.raw.recipe["distractor-capsule"].category = "electromechanics-or-crafting"
data.raw.recipe["destroyer-capsule"].category = "electromechanics-or-crafting"
data.raw.recipe["solar-panel-equipment"].category = "electromechanics-or-crafting"
data.raw.recipe["battery-equipment"].category = "electromechanics-or-crafting"
data.raw.recipe["battery-mk2-equipment"].category = "electromechanics-or-crafting"
data.raw.recipe["battery-mk3-equipment"].category = "electromechanics-or-crafting"
data.raw.recipe["fusion-reactor-equipment"].category = "electromechanics-or-crafting"
data.raw.recipe["fission-reactor-equipment"].category = "advanced-centrifuging-or-crafting-or-electromechanics"
data.raw.recipe["belt-immunity-equipment"].category = "electromechanics-or-crafting"
data.raw.recipe["exoskeleton-equipment"].category = "electromechanics-or-crafting"
data.raw.recipe["personal-roboport-equipment"].category = "electromechanics-or-crafting"
data.raw.recipe["personal-roboport-mk2-equipment"].category = "electromechanics-or-crafting"
data.raw.recipe["night-vision-equipment"].category = "electromechanics-or-crafting"
data.raw.recipe["toolbelt-equipment"].category = "electromechanics-or-crafting"
data.raw.recipe["energy-shield-equipment"].category = "electromechanics-or-crafting"
data.raw.recipe["energy-shield-mk2-equipment"].category = "electromechanics-or-crafting"
data.raw.recipe["personal-laser-defense-equipment"].category = "electromechanics-or-crafting"
data.raw.recipe["discharge-defense-equipment"].category = "electromechanics-or-crafting"
data.raw.recipe["roboport"].category = "electromechanics-or-crafting"
data.raw.recipe["modular-armor"].category = "electromechanics-or-crafting"
data.raw.recipe["power-armor"].category = "electromechanics-or-crafting"
data.raw.recipe["power-armor-mk2"].category = "electromechanics-or-crafting"
data.raw.recipe["mech-armor"].category = "electromechanics-or-crafting"

require "prototypes.advanced-agriculture"
require "prototypes.advanced-assembling-machine"
require "prototypes.advanced-metallurgy"
require "prototypes.arc-furnace"
require "prototypes.atomic-enricher"
require "prototypes.biochemical-facility"
require "prototypes.biomass"
require "prototypes.building-recipes"
require "prototypes.core-miner"
require "prototypes.core-mining"
require "prototypes.electromechanic-facility"
require "prototypes.greenhouse"
require "prototypes.hydraulic-plant"
require "prototypes.item-subgroups"
require "prototypes.lumber-mill"
require "prototypes.miscellaneous-recipes"
require "prototypes.petrochemical-facility"
require "prototypes.petrochemistry"
require "prototypes.quantum-assembler"
require "prototypes.quantum-computer"
require "prototypes.quantum-stabilizer"
require "prototypes.recipe-categories"
require "prototypes.rock-synthesis"
require "prototypes.salvager"
require "prototypes.scrubber"
require "prototypes.scrubbing"
require "prototypes.smeltery"
require "prototypes.technology"
require "prototypes.uranium-sifting"
require "prototypes.woodworking"